"""Core shared helpers for Trestle coordinators.

Owned by the Trestle Coordinator Core team.

Subpackages:
- decision: Pure decision logic (attention, selection, realization, frames)
- transport: IO, wire protocol, network handling
- adapter: Ecosystem adapter boundary (HA, etc.)
"""

__version__ = "0.1.0"

from .adapter import (
    FACT_SCHEMAS,
    INTENT_SCHEMAS,
    AdapterConnectionError,
    AdapterError,
    AdapterHealth,
    AdapterIntentError,
    AdapterTranslationError,
    CanonicalFact,
    CanonicalIntent,
    EcosystemAdapter,
    FactSink,
    FactType,
    IntentType,
)
from .decision import (
    INTERRUPT_THRESHOLD,
    LIFE_SAFETY_THRESHOLD,
    PRIORITY_CRITICAL,
    PRIORITY_GLANCE,
    PRIORITY_INTERRUPT,
    PRIORITY_NOTIFY,
    REALIZATION_PROFILES,
    AlertAction,
    AlertFrame,
    AlertTarget,
    AttentionContext,
    AttentionLevel,
    DecisionContext,
    DecisionTrace,
    DeviceCapabilities,
    DeviceContext,
    EscalationReason,
    OutputChannel,
    RealizationHints,
    RealizationIntent,
    RealizationMode,
    RealizationResult,
    SelectionResult,
    SuppressionReason,
    compute_attention_level,
    compute_attention_level_from_device,
    produce_alert_frame,
    produce_realization_frame,
    realize_alert,
    realize_attention,
    select_device,
    trace_decision,
)
from .errors import (
    TrestleClientError,
    TrestleConnectionError,
    TrestleHandshakeError,
    TrestleResponseError,
    TrestleTimeout,
)
from .transport import (
    TrestleHttpClient,
    TrestleSession,
    TrestleWsClient,
    TrestleWsMessage,
    TrestleWsMessageType,
    build_auth_confirmed,
    build_auth_invalid,
    build_auth_ok,
    build_envelope,
    build_time_body,
    connect_websocket,
    parse_auth_ok,
)

SUPPORTED_PROTOCOL_VERSIONS: tuple[int, ...] = (1,)

__all__ = [
    # Adapter boundary (Slice 7d)
    "FACT_SCHEMAS",
    "INTENT_SCHEMAS",
    # Decision logic
    "INTERRUPT_THRESHOLD",
    "LIFE_SAFETY_THRESHOLD",
    "PRIORITY_CRITICAL",
    "PRIORITY_GLANCE",
    "PRIORITY_INTERRUPT",
    "PRIORITY_NOTIFY",
    "REALIZATION_PROFILES",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "AdapterConnectionError",
    "AdapterError",
    "AdapterHealth",
    "AdapterIntentError",
    "AdapterTranslationError",
    "AlertAction",
    "AlertFrame",
    "AlertTarget",
    "AttentionContext",
    "AttentionLevel",
    "CanonicalFact",
    "CanonicalIntent",
    "DecisionContext",
    "DecisionTrace",
    "DeviceCapabilities",
    "DeviceContext",
    "EcosystemAdapter",
    "EscalationReason",
    "FactSink",
    "FactType",
    "IntentType",
    "OutputChannel",
    "RealizationHints",
    "RealizationIntent",
    "RealizationMode",
    "RealizationResult",
    "SelectionResult",
    "SuppressionReason",
    "TrestleClientError",
    "TrestleConnectionError",
    "TrestleHandshakeError",
    "TrestleHttpClient",
    "TrestleResponseError",
    "TrestleSession",
    "TrestleTimeout",
    "TrestleWsClient",
    "TrestleWsMessage",
    "TrestleWsMessageType",
    "__version__",
    "build_auth_confirmed",
    "build_auth_invalid",
    "build_auth_ok",
    "build_envelope",
    "build_time_body",
    "compute_attention_level",
    "compute_attention_level_from_device",
    "connect_websocket",
    "parse_auth_ok",
    "produce_alert_frame",
    "produce_realization_frame",
    "realize_alert",
    "realize_attention",
    "select_device",
    "trace_decision",
]
