# type: ignore
# This file is auto-generated by protoc and has known __slots__ type issues
# See: https://github.com/protocolbuffers/protobuf/issues/10372
import datetime

from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class AuthRequest(_message.Message):
    __slots__ = ("token", "device_id", "firmware_version")
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    DEVICE_ID_FIELD_NUMBER: _ClassVar[int]
    FIRMWARE_VERSION_FIELD_NUMBER: _ClassVar[int]
    token: str
    device_id: str
    firmware_version: str
    def __init__(
        self,
        token: _Optional[str] = ...,
        device_id: _Optional[str] = ...,
        firmware_version: _Optional[str] = ...,
    ) -> None: ...

class AuthResponse(_message.Message):
    __slots__ = ("success", "error_message", "coordinator_version")
    SUCCESS_FIELD_NUMBER: _ClassVar[int]
    ERROR_MESSAGE_FIELD_NUMBER: _ClassVar[int]
    COORDINATOR_VERSION_FIELD_NUMBER: _ClassVar[int]
    success: bool
    error_message: str
    coordinator_version: str
    def __init__(
        self,
        success: bool = ...,
        error_message: _Optional[str] = ...,
        coordinator_version: _Optional[str] = ...,
    ) -> None: ...

class LayoutPackage(_message.Message):
    __slots__ = (
        "profile_id",
        "profile_version",
        "bindings",
        "layout_data",
        "timestamp",
    )
    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    PROFILE_VERSION_FIELD_NUMBER: _ClassVar[int]
    BINDINGS_FIELD_NUMBER: _ClassVar[int]
    LAYOUT_DATA_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    profile_id: str
    profile_version: str
    bindings: _containers.RepeatedCompositeFieldContainer[Binding]
    layout_data: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        profile_id: _Optional[str] = ...,
        profile_version: _Optional[str] = ...,
        bindings: _Optional[_Iterable[_Union[Binding, _Mapping]]] = ...,
        layout_data: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
    ) -> None: ...

class Binding(_message.Message):
    __slots__ = ("binding_id", "display_name", "entity_type", "attributes")
    BINDING_ID_FIELD_NUMBER: _ClassVar[int]
    DISPLAY_NAME_FIELD_NUMBER: _ClassVar[int]
    ENTITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    ATTRIBUTES_FIELD_NUMBER: _ClassVar[int]
    binding_id: str
    display_name: str
    entity_type: str
    attributes: _struct_pb2.Struct
    def __init__(
        self,
        binding_id: _Optional[str] = ...,
        display_name: _Optional[str] = ...,
        entity_type: _Optional[str] = ...,
        attributes: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...,
    ) -> None: ...

class Snapshot(_message.Message):
    __slots__ = (
        "profile_id",
        "profile_version",
        "fused_facts",
        "timestamp",
        "sequence_number",
    )
    class FusedFactsEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: DomainData
        def __init__(
            self,
            key: _Optional[str] = ...,
            value: _Optional[_Union[DomainData, _Mapping]] = ...,
        ) -> None: ...

    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    PROFILE_VERSION_FIELD_NUMBER: _ClassVar[int]
    FUSED_FACTS_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    SEQUENCE_NUMBER_FIELD_NUMBER: _ClassVar[int]
    profile_id: str
    profile_version: str
    fused_facts: _containers.MessageMap[str, DomainData]
    timestamp: _timestamp_pb2.Timestamp
    sequence_number: int
    def __init__(
        self,
        profile_id: _Optional[str] = ...,
        profile_version: _Optional[str] = ...,
        fused_facts: _Optional[_Mapping[str, DomainData]] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
        sequence_number: _Optional[int] = ...,
    ) -> None: ...

class Delta(_message.Message):
    __slots__ = ("profile_id", "domain", "changes", "timestamp", "sequence_number")
    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    DOMAIN_FIELD_NUMBER: _ClassVar[int]
    CHANGES_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    SEQUENCE_NUMBER_FIELD_NUMBER: _ClassVar[int]
    profile_id: str
    domain: str
    changes: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    sequence_number: int
    def __init__(
        self,
        profile_id: _Optional[str] = ...,
        domain: _Optional[str] = ...,
        changes: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
        sequence_number: _Optional[int] = ...,
    ) -> None: ...

class DomainData(_message.Message):
    __slots__ = ("data",)
    DATA_FIELD_NUMBER: _ClassVar[int]
    data: _struct_pb2.Struct
    def __init__(
        self, data: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...
    ) -> None: ...

class BindingUpdate(_message.Message):
    __slots__ = ("binding_id", "state", "timestamp")
    BINDING_ID_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    binding_id: str
    state: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        binding_id: _Optional[str] = ...,
        state: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
    ) -> None: ...

class Alert(_message.Message):
    __slots__ = (
        "alert_id",
        "profile_id",
        "style",
        "title",
        "message",
        "actions",
        "metadata",
        "timestamp",
    )
    class AlertStyle(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        INFORMATIONAL: _ClassVar[Alert.AlertStyle]
        WARNING: _ClassVar[Alert.AlertStyle]
        CRITICAL: _ClassVar[Alert.AlertStyle]

    INFORMATIONAL: Alert.AlertStyle
    WARNING: Alert.AlertStyle
    CRITICAL: Alert.AlertStyle
    ALERT_ID_FIELD_NUMBER: _ClassVar[int]
    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    STYLE_FIELD_NUMBER: _ClassVar[int]
    TITLE_FIELD_NUMBER: _ClassVar[int]
    MESSAGE_FIELD_NUMBER: _ClassVar[int]
    ACTIONS_FIELD_NUMBER: _ClassVar[int]
    METADATA_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    alert_id: str
    profile_id: str
    style: Alert.AlertStyle
    title: str
    message: str
    actions: _containers.RepeatedCompositeFieldContainer[AlertAction]
    metadata: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        alert_id: _Optional[str] = ...,
        profile_id: _Optional[str] = ...,
        style: _Optional[_Union[Alert.AlertStyle, str]] = ...,
        title: _Optional[str] = ...,
        message: _Optional[str] = ...,
        actions: _Optional[_Iterable[_Union[AlertAction, _Mapping]]] = ...,
        metadata: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
    ) -> None: ...

class AlertAction(_message.Message):
    __slots__ = ("action_id", "label", "is_destructive")
    ACTION_ID_FIELD_NUMBER: _ClassVar[int]
    LABEL_FIELD_NUMBER: _ClassVar[int]
    IS_DESTRUCTIVE_FIELD_NUMBER: _ClassVar[int]
    action_id: str
    label: str
    is_destructive: bool
    def __init__(
        self,
        action_id: _Optional[str] = ...,
        label: _Optional[str] = ...,
        is_destructive: bool = ...,
    ) -> None: ...

class AlertResponse(_message.Message):
    __slots__ = ("alert_id", "action_id", "timestamp")
    ALERT_ID_FIELD_NUMBER: _ClassVar[int]
    ACTION_ID_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    alert_id: str
    action_id: str
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        alert_id: _Optional[str] = ...,
        action_id: _Optional[str] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
    ) -> None: ...

class ActionIntent(_message.Message):
    __slots__ = ("intent_id", "binding_id", "action", "parameters", "timestamp")
    INTENT_ID_FIELD_NUMBER: _ClassVar[int]
    BINDING_ID_FIELD_NUMBER: _ClassVar[int]
    ACTION_FIELD_NUMBER: _ClassVar[int]
    PARAMETERS_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    intent_id: str
    binding_id: str
    action: str
    parameters: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        intent_id: _Optional[str] = ...,
        binding_id: _Optional[str] = ...,
        action: _Optional[str] = ...,
        parameters: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
    ) -> None: ...

class IntentAcknowledgment(_message.Message):
    __slots__ = ("intent_id", "accepted", "error_message")
    INTENT_ID_FIELD_NUMBER: _ClassVar[int]
    ACCEPTED_FIELD_NUMBER: _ClassVar[int]
    ERROR_MESSAGE_FIELD_NUMBER: _ClassVar[int]
    intent_id: str
    accepted: bool
    error_message: str
    def __init__(
        self,
        intent_id: _Optional[str] = ...,
        accepted: bool = ...,
        error_message: _Optional[str] = ...,
    ) -> None: ...

class DeviceStatus(_message.Message):
    __slots__ = (
        "device_id",
        "state",
        "firmware_version",
        "uptime_seconds",
        "free_heap_bytes",
        "wifi_rssi",
        "timestamp",
    )
    class DeviceState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        INITIALIZING: _ClassVar[DeviceStatus.DeviceState]
        PAIRING: _ClassVar[DeviceStatus.DeviceState]
        READY: _ClassVar[DeviceStatus.DeviceState]
        ERROR: _ClassVar[DeviceStatus.DeviceState]

    INITIALIZING: DeviceStatus.DeviceState
    PAIRING: DeviceStatus.DeviceState
    READY: DeviceStatus.DeviceState
    ERROR: DeviceStatus.DeviceState
    DEVICE_ID_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    FIRMWARE_VERSION_FIELD_NUMBER: _ClassVar[int]
    UPTIME_SECONDS_FIELD_NUMBER: _ClassVar[int]
    FREE_HEAP_BYTES_FIELD_NUMBER: _ClassVar[int]
    WIFI_RSSI_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    device_id: str
    state: DeviceStatus.DeviceState
    firmware_version: str
    uptime_seconds: int
    free_heap_bytes: int
    wifi_rssi: int
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        device_id: _Optional[str] = ...,
        state: _Optional[_Union[DeviceStatus.DeviceState, str]] = ...,
        firmware_version: _Optional[str] = ...,
        uptime_seconds: _Optional[int] = ...,
        free_heap_bytes: _Optional[int] = ...,
        wifi_rssi: _Optional[int] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
    ) -> None: ...

class OTANotification(_message.Message):
    __slots__ = (
        "version",
        "download_url",
        "checksum_sha256",
        "size_bytes",
        "changelog",
        "mandatory",
    )
    VERSION_FIELD_NUMBER: _ClassVar[int]
    DOWNLOAD_URL_FIELD_NUMBER: _ClassVar[int]
    CHECKSUM_SHA256_FIELD_NUMBER: _ClassVar[int]
    SIZE_BYTES_FIELD_NUMBER: _ClassVar[int]
    CHANGELOG_FIELD_NUMBER: _ClassVar[int]
    MANDATORY_FIELD_NUMBER: _ClassVar[int]
    version: str
    download_url: str
    checksum_sha256: str
    size_bytes: int
    changelog: str
    mandatory: bool
    def __init__(
        self,
        version: _Optional[str] = ...,
        download_url: _Optional[str] = ...,
        checksum_sha256: _Optional[str] = ...,
        size_bytes: _Optional[int] = ...,
        changelog: _Optional[str] = ...,
        mandatory: bool = ...,
    ) -> None: ...

class OTAProgress(_message.Message):
    __slots__ = ("progress_percent", "state", "error_message")
    class OTAState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        DOWNLOADING: _ClassVar[OTAProgress.OTAState]
        VERIFYING: _ClassVar[OTAProgress.OTAState]
        INSTALLING: _ClassVar[OTAProgress.OTAState]
        COMPLETED: _ClassVar[OTAProgress.OTAState]
        FAILED: _ClassVar[OTAProgress.OTAState]

    DOWNLOADING: OTAProgress.OTAState
    VERIFYING: OTAProgress.OTAState
    INSTALLING: OTAProgress.OTAState
    COMPLETED: OTAProgress.OTAState
    FAILED: OTAProgress.OTAState
    PROGRESS_PERCENT_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    ERROR_MESSAGE_FIELD_NUMBER: _ClassVar[int]
    progress_percent: int
    state: OTAProgress.OTAState
    error_message: str
    def __init__(
        self,
        progress_percent: _Optional[int] = ...,
        state: _Optional[_Union[OTAProgress.OTAState, str]] = ...,
        error_message: _Optional[str] = ...,
    ) -> None: ...

class Message(_message.Message):
    __slots__ = (
        "message_id",
        "timestamp",
        "auth_request",
        "auth_response",
        "layout_package",
        "snapshot",
        "delta",
        "binding_update",
        "alert",
        "alert_response",
        "action_intent",
        "intent_ack",
        "device_status",
        "ota_notification",
        "ota_progress",
    )
    MESSAGE_ID_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    AUTH_REQUEST_FIELD_NUMBER: _ClassVar[int]
    AUTH_RESPONSE_FIELD_NUMBER: _ClassVar[int]
    LAYOUT_PACKAGE_FIELD_NUMBER: _ClassVar[int]
    SNAPSHOT_FIELD_NUMBER: _ClassVar[int]
    DELTA_FIELD_NUMBER: _ClassVar[int]
    BINDING_UPDATE_FIELD_NUMBER: _ClassVar[int]
    ALERT_FIELD_NUMBER: _ClassVar[int]
    ALERT_RESPONSE_FIELD_NUMBER: _ClassVar[int]
    ACTION_INTENT_FIELD_NUMBER: _ClassVar[int]
    INTENT_ACK_FIELD_NUMBER: _ClassVar[int]
    DEVICE_STATUS_FIELD_NUMBER: _ClassVar[int]
    OTA_NOTIFICATION_FIELD_NUMBER: _ClassVar[int]
    OTA_PROGRESS_FIELD_NUMBER: _ClassVar[int]
    message_id: str
    timestamp: _timestamp_pb2.Timestamp
    auth_request: AuthRequest
    auth_response: AuthResponse
    layout_package: LayoutPackage
    snapshot: Snapshot
    delta: Delta
    binding_update: BindingUpdate
    alert: Alert
    alert_response: AlertResponse
    action_intent: ActionIntent
    intent_ack: IntentAcknowledgment
    device_status: DeviceStatus
    ota_notification: OTANotification
    ota_progress: OTAProgress
    def __init__(
        self,
        message_id: _Optional[str] = ...,
        timestamp: _Optional[
            _Union[datetime.datetime, _timestamp_pb2.Timestamp, _Mapping]
        ] = ...,
        auth_request: _Optional[_Union[AuthRequest, _Mapping]] = ...,
        auth_response: _Optional[_Union[AuthResponse, _Mapping]] = ...,
        layout_package: _Optional[_Union[LayoutPackage, _Mapping]] = ...,
        snapshot: _Optional[_Union[Snapshot, _Mapping]] = ...,
        delta: _Optional[_Union[Delta, _Mapping]] = ...,
        binding_update: _Optional[_Union[BindingUpdate, _Mapping]] = ...,
        alert: _Optional[_Union[Alert, _Mapping]] = ...,
        alert_response: _Optional[_Union[AlertResponse, _Mapping]] = ...,
        action_intent: _Optional[_Union[ActionIntent, _Mapping]] = ...,
        intent_ack: _Optional[_Union[IntentAcknowledgment, _Mapping]] = ...,
        device_status: _Optional[_Union[DeviceStatus, _Mapping]] = ...,
        ota_notification: _Optional[_Union[OTANotification, _Mapping]] = ...,
        ota_progress: _Optional[_Union[OTAProgress, _Mapping]] = ...,
    ) -> None: ...
