# type: ignore
# This file is auto-generated by protoc and has known __slots__ type issues
# See: https://github.com/protocolbuffers/protobuf/issues/10372
import datetime
from collections.abc import Iterable as _Iterable
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

DESCRIPTOR: _descriptor.FileDescriptor

class AuthRequest(_message.Message):
    __slots__ = ("device_id", "firmware_version", "token")
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    DEVICE_ID_FIELD_NUMBER: _ClassVar[int]
    FIRMWARE_VERSION_FIELD_NUMBER: _ClassVar[int]
    token: str
    device_id: str
    firmware_version: str
    def __init__(
        self,
        token: str | None = ...,
        device_id: str | None = ...,
        firmware_version: str | None = ...,
    ) -> None: ...

class AuthResponse(_message.Message):
    __slots__ = ("coordinator_version", "error_message", "success")
    SUCCESS_FIELD_NUMBER: _ClassVar[int]
    ERROR_MESSAGE_FIELD_NUMBER: _ClassVar[int]
    COORDINATOR_VERSION_FIELD_NUMBER: _ClassVar[int]
    success: bool
    error_message: str
    coordinator_version: str
    def __init__(
        self,
        success: bool = ...,
        error_message: str | None = ...,
        coordinator_version: str | None = ...,
    ) -> None: ...

class LayoutPackage(_message.Message):
    __slots__ = (
        "bindings",
        "layout_data",
        "profile_id",
        "profile_version",
        "timestamp",
    )
    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    PROFILE_VERSION_FIELD_NUMBER: _ClassVar[int]
    BINDINGS_FIELD_NUMBER: _ClassVar[int]
    LAYOUT_DATA_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    profile_id: str
    profile_version: str
    bindings: _containers.RepeatedCompositeFieldContainer[Binding]
    layout_data: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        profile_id: str | None = ...,
        profile_version: str | None = ...,
        bindings: _Iterable[Binding | _Mapping] | None = ...,
        layout_data: _struct_pb2.Struct | _Mapping | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
    ) -> None: ...

class Binding(_message.Message):
    __slots__ = ("attributes", "binding_id", "display_name", "entity_type")
    BINDING_ID_FIELD_NUMBER: _ClassVar[int]
    DISPLAY_NAME_FIELD_NUMBER: _ClassVar[int]
    ENTITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    ATTRIBUTES_FIELD_NUMBER: _ClassVar[int]
    binding_id: str
    display_name: str
    entity_type: str
    attributes: _struct_pb2.Struct
    def __init__(
        self,
        binding_id: str | None = ...,
        display_name: str | None = ...,
        entity_type: str | None = ...,
        attributes: _struct_pb2.Struct | _Mapping | None = ...,
    ) -> None: ...

class Snapshot(_message.Message):
    __slots__ = (
        "fused_facts",
        "profile_id",
        "profile_version",
        "sequence_number",
        "timestamp",
    )
    class FusedFactsEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: DomainData
        def __init__(
            self,
            key: str | None = ...,
            value: DomainData | _Mapping | None = ...,
        ) -> None: ...

    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    PROFILE_VERSION_FIELD_NUMBER: _ClassVar[int]
    FUSED_FACTS_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    SEQUENCE_NUMBER_FIELD_NUMBER: _ClassVar[int]
    profile_id: str
    profile_version: str
    fused_facts: _containers.MessageMap[str, DomainData]
    timestamp: _timestamp_pb2.Timestamp
    sequence_number: int
    def __init__(
        self,
        profile_id: str | None = ...,
        profile_version: str | None = ...,
        fused_facts: _Mapping[str, DomainData] | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
        sequence_number: int | None = ...,
    ) -> None: ...

class Delta(_message.Message):
    __slots__ = ("changes", "domain", "profile_id", "sequence_number", "timestamp")
    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    DOMAIN_FIELD_NUMBER: _ClassVar[int]
    CHANGES_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    SEQUENCE_NUMBER_FIELD_NUMBER: _ClassVar[int]
    profile_id: str
    domain: str
    changes: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    sequence_number: int
    def __init__(
        self,
        profile_id: str | None = ...,
        domain: str | None = ...,
        changes: _struct_pb2.Struct | _Mapping | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
        sequence_number: int | None = ...,
    ) -> None: ...

class DomainData(_message.Message):
    __slots__ = ("data",)
    DATA_FIELD_NUMBER: _ClassVar[int]
    data: _struct_pb2.Struct
    def __init__(self, data: _struct_pb2.Struct | _Mapping | None = ...) -> None: ...

class BindingUpdate(_message.Message):
    __slots__ = ("binding_id", "state", "timestamp")
    BINDING_ID_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    binding_id: str
    state: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        binding_id: str | None = ...,
        state: _struct_pb2.Struct | _Mapping | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
    ) -> None: ...

class Alert(_message.Message):
    __slots__ = (
        "actions",
        "alert_id",
        "message",
        "metadata",
        "profile_id",
        "style",
        "timestamp",
        "title",
    )
    class AlertStyle(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        INFORMATIONAL: _ClassVar[Alert.AlertStyle]
        WARNING: _ClassVar[Alert.AlertStyle]
        CRITICAL: _ClassVar[Alert.AlertStyle]

    INFORMATIONAL: Alert.AlertStyle
    WARNING: Alert.AlertStyle
    CRITICAL: Alert.AlertStyle
    ALERT_ID_FIELD_NUMBER: _ClassVar[int]
    PROFILE_ID_FIELD_NUMBER: _ClassVar[int]
    STYLE_FIELD_NUMBER: _ClassVar[int]
    TITLE_FIELD_NUMBER: _ClassVar[int]
    MESSAGE_FIELD_NUMBER: _ClassVar[int]
    ACTIONS_FIELD_NUMBER: _ClassVar[int]
    METADATA_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    alert_id: str
    profile_id: str
    style: Alert.AlertStyle
    title: str
    message: str
    actions: _containers.RepeatedCompositeFieldContainer[AlertAction]
    metadata: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        alert_id: str | None = ...,
        profile_id: str | None = ...,
        style: Alert.AlertStyle | str | None = ...,
        title: str | None = ...,
        message: str | None = ...,
        actions: _Iterable[AlertAction | _Mapping] | None = ...,
        metadata: _struct_pb2.Struct | _Mapping | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
    ) -> None: ...

class AlertAction(_message.Message):
    __slots__ = ("action_id", "is_destructive", "label")
    ACTION_ID_FIELD_NUMBER: _ClassVar[int]
    LABEL_FIELD_NUMBER: _ClassVar[int]
    IS_DESTRUCTIVE_FIELD_NUMBER: _ClassVar[int]
    action_id: str
    label: str
    is_destructive: bool
    def __init__(
        self,
        action_id: str | None = ...,
        label: str | None = ...,
        is_destructive: bool = ...,
    ) -> None: ...

class AlertResponse(_message.Message):
    __slots__ = ("action_id", "alert_id", "timestamp")
    ALERT_ID_FIELD_NUMBER: _ClassVar[int]
    ACTION_ID_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    alert_id: str
    action_id: str
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        alert_id: str | None = ...,
        action_id: str | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
    ) -> None: ...

class ActionIntent(_message.Message):
    __slots__ = ("action", "binding_id", "intent_id", "parameters", "timestamp")
    INTENT_ID_FIELD_NUMBER: _ClassVar[int]
    BINDING_ID_FIELD_NUMBER: _ClassVar[int]
    ACTION_FIELD_NUMBER: _ClassVar[int]
    PARAMETERS_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    intent_id: str
    binding_id: str
    action: str
    parameters: _struct_pb2.Struct
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        intent_id: str | None = ...,
        binding_id: str | None = ...,
        action: str | None = ...,
        parameters: _struct_pb2.Struct | _Mapping | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
    ) -> None: ...

class IntentAcknowledgment(_message.Message):
    __slots__ = ("accepted", "error_message", "intent_id")
    INTENT_ID_FIELD_NUMBER: _ClassVar[int]
    ACCEPTED_FIELD_NUMBER: _ClassVar[int]
    ERROR_MESSAGE_FIELD_NUMBER: _ClassVar[int]
    intent_id: str
    accepted: bool
    error_message: str
    def __init__(
        self,
        intent_id: str | None = ...,
        accepted: bool = ...,
        error_message: str | None = ...,
    ) -> None: ...

class DeviceStatus(_message.Message):
    __slots__ = (
        "device_id",
        "firmware_version",
        "free_heap_bytes",
        "state",
        "timestamp",
        "uptime_seconds",
        "wifi_rssi",
    )
    class DeviceState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        INITIALIZING: _ClassVar[DeviceStatus.DeviceState]
        PAIRING: _ClassVar[DeviceStatus.DeviceState]
        READY: _ClassVar[DeviceStatus.DeviceState]
        ERROR: _ClassVar[DeviceStatus.DeviceState]

    INITIALIZING: DeviceStatus.DeviceState
    PAIRING: DeviceStatus.DeviceState
    READY: DeviceStatus.DeviceState
    ERROR: DeviceStatus.DeviceState
    DEVICE_ID_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    FIRMWARE_VERSION_FIELD_NUMBER: _ClassVar[int]
    UPTIME_SECONDS_FIELD_NUMBER: _ClassVar[int]
    FREE_HEAP_BYTES_FIELD_NUMBER: _ClassVar[int]
    WIFI_RSSI_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    device_id: str
    state: DeviceStatus.DeviceState
    firmware_version: str
    uptime_seconds: int
    free_heap_bytes: int
    wifi_rssi: int
    timestamp: _timestamp_pb2.Timestamp
    def __init__(
        self,
        device_id: str | None = ...,
        state: DeviceStatus.DeviceState | str | None = ...,
        firmware_version: str | None = ...,
        uptime_seconds: int | None = ...,
        free_heap_bytes: int | None = ...,
        wifi_rssi: int | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
    ) -> None: ...

class OTANotification(_message.Message):
    __slots__ = (
        "changelog",
        "checksum_sha256",
        "download_url",
        "mandatory",
        "size_bytes",
        "version",
    )
    VERSION_FIELD_NUMBER: _ClassVar[int]
    DOWNLOAD_URL_FIELD_NUMBER: _ClassVar[int]
    CHECKSUM_SHA256_FIELD_NUMBER: _ClassVar[int]
    SIZE_BYTES_FIELD_NUMBER: _ClassVar[int]
    CHANGELOG_FIELD_NUMBER: _ClassVar[int]
    MANDATORY_FIELD_NUMBER: _ClassVar[int]
    version: str
    download_url: str
    checksum_sha256: str
    size_bytes: int
    changelog: str
    mandatory: bool
    def __init__(
        self,
        version: str | None = ...,
        download_url: str | None = ...,
        checksum_sha256: str | None = ...,
        size_bytes: int | None = ...,
        changelog: str | None = ...,
        mandatory: bool = ...,
    ) -> None: ...

class OTAProgress(_message.Message):
    __slots__ = ("error_message", "progress_percent", "state")
    class OTAState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        DOWNLOADING: _ClassVar[OTAProgress.OTAState]
        VERIFYING: _ClassVar[OTAProgress.OTAState]
        INSTALLING: _ClassVar[OTAProgress.OTAState]
        COMPLETED: _ClassVar[OTAProgress.OTAState]
        FAILED: _ClassVar[OTAProgress.OTAState]

    DOWNLOADING: OTAProgress.OTAState
    VERIFYING: OTAProgress.OTAState
    INSTALLING: OTAProgress.OTAState
    COMPLETED: OTAProgress.OTAState
    FAILED: OTAProgress.OTAState
    PROGRESS_PERCENT_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    ERROR_MESSAGE_FIELD_NUMBER: _ClassVar[int]
    progress_percent: int
    state: OTAProgress.OTAState
    error_message: str
    def __init__(
        self,
        progress_percent: int | None = ...,
        state: OTAProgress.OTAState | str | None = ...,
        error_message: str | None = ...,
    ) -> None: ...

class Message(_message.Message):
    __slots__ = (
        "action_intent",
        "alert",
        "alert_response",
        "auth_request",
        "auth_response",
        "binding_update",
        "delta",
        "device_status",
        "intent_ack",
        "layout_package",
        "message_id",
        "ota_notification",
        "ota_progress",
        "snapshot",
        "timestamp",
    )
    MESSAGE_ID_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    AUTH_REQUEST_FIELD_NUMBER: _ClassVar[int]
    AUTH_RESPONSE_FIELD_NUMBER: _ClassVar[int]
    LAYOUT_PACKAGE_FIELD_NUMBER: _ClassVar[int]
    SNAPSHOT_FIELD_NUMBER: _ClassVar[int]
    DELTA_FIELD_NUMBER: _ClassVar[int]
    BINDING_UPDATE_FIELD_NUMBER: _ClassVar[int]
    ALERT_FIELD_NUMBER: _ClassVar[int]
    ALERT_RESPONSE_FIELD_NUMBER: _ClassVar[int]
    ACTION_INTENT_FIELD_NUMBER: _ClassVar[int]
    INTENT_ACK_FIELD_NUMBER: _ClassVar[int]
    DEVICE_STATUS_FIELD_NUMBER: _ClassVar[int]
    OTA_NOTIFICATION_FIELD_NUMBER: _ClassVar[int]
    OTA_PROGRESS_FIELD_NUMBER: _ClassVar[int]
    message_id: str
    timestamp: _timestamp_pb2.Timestamp
    auth_request: AuthRequest
    auth_response: AuthResponse
    layout_package: LayoutPackage
    snapshot: Snapshot
    delta: Delta
    binding_update: BindingUpdate
    alert: Alert
    alert_response: AlertResponse
    action_intent: ActionIntent
    intent_ack: IntentAcknowledgment
    device_status: DeviceStatus
    ota_notification: OTANotification
    ota_progress: OTAProgress
    def __init__(
        self,
        message_id: str | None = ...,
        timestamp: datetime.datetime | _timestamp_pb2.Timestamp | _Mapping | None = ...,
        auth_request: AuthRequest | _Mapping | None = ...,
        auth_response: AuthResponse | _Mapping | None = ...,
        layout_package: LayoutPackage | _Mapping | None = ...,
        snapshot: Snapshot | _Mapping | None = ...,
        delta: Delta | _Mapping | None = ...,
        binding_update: BindingUpdate | _Mapping | None = ...,
        alert: Alert | _Mapping | None = ...,
        alert_response: AlertResponse | _Mapping | None = ...,
        action_intent: ActionIntent | _Mapping | None = ...,
        intent_ack: IntentAcknowledgment | _Mapping | None = ...,
        device_status: DeviceStatus | _Mapping | None = ...,
        ota_notification: OTANotification | _Mapping | None = ...,
        ota_progress: OTAProgress | _Mapping | None = ...,
    ) -> None: ...
